#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

: ${TEST_NAMESPACE:?"Need to set TEST_NAMESPACE"}
: ${POD_NAME:?"Need to set POD_NAME"}
: ${KUBECONFIG:?"Need to set KUBECONFIG"}
: ${TEST_POD_SPEC:?"Need to set TEST_POD_SPEC"}

# Setup RBAC for the e2e tests
source hack/ci/rbac_utils.sh
function cleanup {
    rbac_cleanup
    kubectl -n ${TEST_NAMESPACE} delete pod ${POD_NAME}
}
trap cleanup EXIT

if rbac_setup ; then
    echo "RBAC setup success! ==="
else
    echo "RBAC setup fail! ==="
    exit 1
fi
go build -o logcollector test/logcollector/main.go
kubectl -n ${TEST_NAMESPACE} create -f ${TEST_POD_SPEC}

# Wait until pod is running or timeout
echo "Waiting for test-pod to start running"
if kubectl -n ${TEST_NAMESPACE} wait --timeout=180s --for=condition=ContainersReady pod ${POD_NAME}; then
   echo "Pod ${POD_NAME} is running"
else
    echo "Timeout waiting for test-pod ${POD_NAME} to become running"
    echo "=============="
    kubectl -n ${TEST_NAMESPACE} logs ${POD_NAME}
    echo "=============="
    kubectl -n ${TEST_NAMESPACE} describe pod ${POD_NAME}
    echo "=============="
    exit 1
fi

# Print out and save logs to a file until the pod stops running
echo "collecting logs =========="

DOCKER_REPO_ROOT="/go/src/github.com/on2itsecurity/etcd-operator"
mkdir -p _output/logs/
cp $KUBECONFIG ./kubeconfig

./logcollector --kubeconfig=$KUBECONFIG --e2e-podname=${POD_NAME} \
    --namespace=${TEST_NAMESPACE} --logs-dir="_output/logs/"

PHASE_SUCCEEDED="Succeeded"

# Check for pod success or failure
POD_PHASE=$(kubectl -n ${TEST_NAMESPACE} get pod ${POD_NAME} -o jsonpath='{.status.phase}')
if [ "${POD_PHASE}" == "${PHASE_SUCCEEDED}" ]; then
    echo "e2e tests finished successfully"
else
    echo "e2e tests failed"
    kubectl -n ${TEST_NAMESPACE} describe pod ${POD_NAME}
    exit 1
fi
