name: Docker image
on:
  pull_request:
  push:
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3.0.2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        export PATH=$PATH:/home/runner/go/bin

    - name: Build operators
      run: |
        hack/build/operator/build
        hack/build/backup-operator/build
        hack/build/restore-operator/build

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v3
      with:
       images: lthub/etcd-operator
       # generate Docker tags based on the following events/attributes
       tags: |
         type=schedule
         type=ref,event=branch
         type=ref,event=pr
         type=ref,event=tag
         type=semver,pattern={{version}}
         type=semver,pattern={{major}}.{{minor}}
         type=semver,pattern={{major}}
         type=sha

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./hack/build/Dockerfile
        push: ${{ github.event_name != 'pull_request'  }}
        tags: ${{ steps.meta.outputs.tags  }}
        labels: ${{ steps.meta.outputs.labels  }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
